name: PHP CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3' # You can choose the version you want here

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHPUnit tests
      run: bin/phpunit
